package eu.zunix.ore_and_alloy.datagen.material;

import eu.zunix.ore_and_alloy.core.GemMaterial;
import eu.zunix.ore_and_alloy.core.MaterialForm;
import eu.zunix.ore_and_alloy.core.MaterialFormCatalog;
import eu.zunix.ore_and_alloy.core.GemMaterialFormRules;
import eu.zunix.ore_and_alloy.core.MaterialItemOrder;
import eu.zunix.ore_and_alloy.core.MetalMaterial;
import eu.zunix.ore_and_alloy.core.RawMaterialMappings;
import eu.zunix.ore_and_alloy.registry.ModStandaloneItems;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

public final class MaterialItemCollector {
    private final String namespace;
    private final Path mainResources;

    public MaterialItemCollector(String namespace, Path mainResources) {
        this.namespace = namespace;
        this.mainResources = mainResources;
    }

    public List<String> collectMaterialItems() throws IOException {
        LinkedHashSet<String> items = new LinkedHashSet<>();
        Path itemTextureRoot = mainResources.resolve(Path.of("assets", namespace, "textures", "item"));
        if (!Files.isDirectory(itemTextureRoot)) return List.of();

        try (var dirs = Files.list(itemTextureRoot)) {
            for (Path dir : dirs.toList()) {
                if (!Files.isDirectory(dir)) continue;
                String form = dir.getFileName().toString().toLowerCase(Locale.ROOT);

                try (var files = Files.list(dir)) {
                    for (Path file : files.toList()) {
                        if (!Files.isRegularFile(file)) continue;
                        String fileName = file.getFileName().toString().toLowerCase(Locale.ROOT);
                        if (!fileName.endsWith(".png")) continue;

                        String textureId = fileName.substring(0, fileName.length() - 4);
                        String itemId = MaterialIdParser.deriveItemIdFromTextureFile(form, textureId);
                        if (!itemId.isBlank() && !isStandaloneMaterialItemId(itemId) && isAllowedMaterialItemForm(itemId)) {
                            items.add(itemId);
                        }
                    }
                }
            }
        }

        List<String> sorted = new ArrayList<>(items);
        addGuaranteedMaterialForms(sorted);
        sorted.sort(MaterialItemOrder.comparator());
        return sorted;
    }

    public void writeMaterialManifest(Path mainResRoot, List<String> materialItems) throws IOException {
        Path manifest = mainResRoot.resolve(Path.of("assets", namespace, "material_items.txt"));
        StringBuilder sb = new StringBuilder();
        sb.append("# Auto-generated by MaterialDataGenerator\n");
        sb.append("# Register only items that have ready textures in assets/").append(namespace).append("/textures/item/<form>/\n");
        for (String item : materialItems) {
            sb.append(item).append('\n');
        }
        DatagenFiles.writeText(manifest, sb.toString());
    }

    private static boolean isStandaloneMaterialItemId(String itemId) {
        if (ModStandaloneItems.isStandaloneItemId(itemId)) {
            return true;
        }
        try {
            MaterialId parsed = MaterialIdParser.parseItemId(itemId);
            return ModStandaloneItems.isStandaloneMaterialToken(parsed.material());
        } catch (IllegalArgumentException ignored) {
            return false;
        }
    }

    private static void addGuaranteedMaterialForms(List<String> items) {
        Map<String, String> preferredTokens = preferredMaterialTokens(items);
        Map<String, Set<String>> discoveredFormsByMaterial = discoveredFormsByMaterial(items);
        LinkedHashSet<String> set = new LinkedHashSet<>();

        for (String id : items) {
            MaterialId parsed = MaterialIdParser.parseItemId(id);
            if (!GemMaterialFormRules.isAllowed(parsed.material(), parsed.form())) continue;
            String material = preferredMaterialToken(preferredTokens, parsed.material());
            set.add(MaterialIdParser.itemIdFor(material, parsed.form()));
        }

        for (Map.Entry<String, Set<String>> entry : discoveredFormsByMaterial.entrySet()) {
            String material = preferredMaterialToken(preferredTokens, entry.getKey());
            Set<String> forms = entry.getValue();

            if (forms.contains("ingot")) {
                for (String form : MaterialFormCatalog.METAL_SET_FORMS) {
                    set.add(MaterialIdParser.itemIdFor(material, form));
                }
            }

            if (forms.contains("gem")) {
                for (String form : MaterialFormCatalog.GEM_SET_FORMS) {
                    set.add(MaterialIdParser.itemIdFor(material, form));
                }
            }

            set.add(MaterialIdParser.itemIdFor(material, "shard"));
        }

        for (MetalMaterial metal : MetalMaterial.values()) {
            String material = preferredMaterialToken(preferredTokens, metal.materialName());
            set.add(MaterialIdParser.itemIdFor(material, "dirty_dust"));
            set.add(MaterialIdParser.itemIdFor(material, "clump"));
            set.add(MaterialIdParser.itemIdFor(material, "shard"));
            set.add(MaterialIdParser.itemIdFor(material, "ring"));
            set.add(MaterialIdParser.itemIdFor(material, "spring"));
            if (metal.getForms().contains(MaterialForm.RAW)) {
                set.addAll(RawMaterialMappings.rawItemIdsForMaterial(material));
            }
            if (metal.getForms().contains(MaterialForm.CRUSHED)) {
                set.addAll(RawMaterialMappings.crushedItemIdsForMaterial(material));
            }
        }
        for (GemMaterial gem : GemMaterial.values()) {
            String material = preferredMaterialToken(preferredTokens, gem.name().toLowerCase(Locale.ROOT));
            for (var form : gem.getForms()) {
                String formName = form.name().toLowerCase(Locale.ROOT);
                if ("raw".equals(formName)) {
                    set.addAll(RawMaterialMappings.rawItemIdsForMaterial(material));
                    continue;
                }
                if ("crushed".equals(formName)) {
                    set.addAll(RawMaterialMappings.crushedItemIdsForMaterial(material));
                    continue;
                }
                set.add(MaterialIdParser.itemIdFor(material, formName));
            }
            set.add(MaterialIdParser.itemIdFor(material, "dirty_dust"));
            set.add(MaterialIdParser.itemIdFor(material, "clump"));
            set.add(MaterialIdParser.itemIdFor(material, "shard"));
            set.add(MaterialIdParser.itemIdFor(material, "ring"));
            set.add(MaterialIdParser.itemIdFor(material, "spring"));
        }

        items.clear();
        items.addAll(set);
    }

    private static Map<String, String> preferredMaterialTokens(List<String> itemIds) {
        Map<String, String> out = new LinkedHashMap<>();
        for (String id : itemIds) {
            MaterialId parsed = MaterialIdParser.parseItemId(id);
            String token = parsed.material();
            String canonical = MaterialItemOrder.canonicalMaterialToken(token);
            String previous = out.get(canonical);
            if (previous == null || shouldPreferToken(token, previous, canonical)) {
                out.put(canonical, token);
            }
        }
        return out;
    }

    private static Map<String, Set<String>> discoveredFormsByMaterial(List<String> itemIds) {
        Map<String, Set<String>> out = new LinkedHashMap<>();
        for (String id : itemIds) {
            MaterialId parsed = MaterialIdParser.parseItemId(id);
            if (!GemMaterialFormRules.isAllowed(parsed.material(), parsed.form())) continue;
            String material = MaterialItemOrder.canonicalMaterialToken(parsed.material());
            out.computeIfAbsent(material, ignored -> new LinkedHashSet<>()).add(parsed.form());
        }
        return out;
    }

    private static boolean isAllowedMaterialItemForm(String itemId) {
        try {
            MaterialId parsed = MaterialIdParser.parseItemId(itemId);
            return GemMaterialFormRules.isAllowed(parsed.material(), parsed.form());
        } catch (IllegalArgumentException ignored) {
            return true;
        }
    }

    private static boolean shouldPreferToken(String candidate, String existing, String canonical) {
        return canonical.equals(candidate) && !canonical.equals(existing);
    }

    private static String preferredMaterialToken(Map<String, String> preferredTokens, String material) {
        String canonical = MaterialItemOrder.canonicalMaterialToken(material);
        return preferredTokens.getOrDefault(canonical, canonical);
    }
}
